// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.lp.dto;

import lombok.Data;

/**
 * ws 发送接收消息
 *
 * @author 10263
 */
@Data
public class Message<T> {
    //路径
    private String path;
    //服务名
    private String serverName;
    //具体数据信息
    private T data;

}
